/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package secure_coding;

import java.security.KeyManagementException;
import java.security.NoSuchAlgorithmException;

import javax.net.ssl.SSLContext;
import javax.net.ssl.TrustManager;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) throws NoSuchAlgorithmException, KeyManagementException {
        System.out.println(new App().getGreeting());

        SSLContext context = SSLContext.getInstance("TLS");
        TrustManager[] trustManager = new TrustManager[] { new TrustManagerImpl() };
        context.init(null, trustManager, null); 
    }
}
